name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js (LTS)
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'

    - name: Install frontend dependencies
      run: npm install
      working-directory: frontend

    - name: Install backend dependencies
      run: npm install
      working-directory: backend

    - name: Run frontend start script
      run: npm run start
      working-directory: frontend

    - name: Run backend start script
      run: npm run start
      working-directory: backend
