name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install frontend dependencies
      run: npm install
      working-directory: frontend

    - name: Install backend dependencies
      run: npm install
      working-directory: backend

    - name: Run frontend start script
      run: npm run start
      working-directory: frontend

    - name: Run backend start script
      run: npm run start
      working-directory: backend
